# still creating compose build
version: '3'
services:
  ifirlana:
    image: ifirlana/docker-angular7:test
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M